# Generated by Django 3.1.3 on 2020-12-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='Mid',
        ),
    ]
