# Generated by Django 3.1.3 on 2020-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0002_auto_20201202_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
